name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Publish Docker Action
      uses: jerray/publish-docker-action@v1.0.3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        repository: relative/mirage
        auto_tag: true
        allow_pull_request: false
